//! Invariant tests for the approximation algorithms.
//!
//! Approximation routines are heuristics: their specific output need not match
//! any particular reference, so an exact NetworkX oracle is not meaningful.
//! What must always hold is the defining structural property of each result.
//! These tests assert exactly those invariants over a deterministic, seeded
//! family of graphs:
//!
//!   - `min_weighted_vertex_cover` returns a set covering every edge.
//!   - `maximum_independent_set` returns a set with no two adjacent nodes.
//!   - `max_clique` returns a set in which every pair is adjacent.
//!   - `min_maximal_matching` returns vertex-disjoint edges of the graph.
//!   - `ramsey_r2` returns a valid clique and a valid independent set.
//!   - `approximate_diameter` (an exact computation despite its name) equals the
//!     true diameter computed by brute-force BFS on connected graphs.
//!
//! The graphs are generated by a small linear-congruential generator so the
//! suite is fully deterministic without depending on `rand`.

#![cfg(feature = "approximation")]

use graphina::approximation::clique::max_clique;
use graphina::approximation::diameter::approximate_diameter;
use graphina::approximation::independent_set::maximum_independent_set;
use graphina::approximation::matching::min_maximal_matching;
use graphina::approximation::ramsey::ramsey_r2;
use graphina::approximation::vertex_cover::min_weighted_vertex_cover;
use graphina::core::types::{Graph, NodeId};
use ordered_float::OrderedFloat;
use std::collections::{HashSet, VecDeque};

/// Deterministic linear-congruential generator (Numerical Recipes constants).
struct Lcg(u64);
impl Lcg {
    fn next_u64(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0
    }
    fn chance(&mut self, p: f64) -> bool {
        (self.next_u64() >> 11) as f64 / ((1u64 << 53) as f64) < p
    }
    fn range(&mut self, lo: usize, hi: usize) -> usize {
        lo + (self.next_u64() as usize) % (hi - lo + 1)
    }
}

/// One generated graph: its node count and the undirected edge list (u < v).
struct Spec {
    n: usize,
    edges: Vec<(usize, usize)>,
}

/// A family of simple undirected graphs spanning a range of sizes and
/// densities, including sparse (often disconnected) and dense cases.
fn graph_specs() -> Vec<Spec> {
    let mut rng = Lcg(0x5EED_A99C_0DEF);
    let densities = [0.1, 0.25, 0.5, 0.75];
    let mut specs = Vec::new();
    for _ in 0..40 {
        let n = rng.range(3, 12);
        let density = densities[rng.range(0, densities.len() - 1)];
        let mut edges = Vec::new();
        for u in 0..n {
            for v in (u + 1)..n {
                if rng.chance(density) {
                    edges.push((u, v));
                }
            }
        }
        specs.push(Spec { n, edges });
    }
    specs
}

/// Specs restricted to connected graphs, built as a random spanning path plus
/// extra edges, so distance-based metrics are defined.
fn connected_specs() -> Vec<Spec> {
    let mut rng = Lcg(0xC0FF_EE12_3456);
    let densities = [0.1, 0.3, 0.6];
    let mut specs = Vec::new();
    for _ in 0..30 {
        let n = rng.range(2, 12);
        let mut edge_set: HashSet<(usize, usize)> = HashSet::new();
        // Spanning path 0-1-2-...-(n-1) guarantees connectivity.
        for u in 0..n.saturating_sub(1) {
            edge_set.insert((u, u + 1));
        }
        let density = densities[rng.range(0, densities.len() - 1)];
        for u in 0..n {
            for v in (u + 1)..n {
                if rng.chance(density) {
                    edge_set.insert((u, v));
                }
            }
        }
        let mut edges: Vec<(usize, usize)> = edge_set.into_iter().collect();
        edges.sort_unstable();
        specs.push(Spec { n, edges });
    }
    specs
}

fn build(spec: &Spec) -> (Graph<i32, f64>, Vec<NodeId>) {
    let mut g: Graph<i32, f64> = Graph::new();
    let ids: Vec<NodeId> = (0..spec.n).map(|i| g.add_node(i as i32)).collect();
    for &(u, v) in &spec.edges {
        g.add_edge(ids[u], ids[v], 1.0);
    }
    (g, ids)
}

fn adjacency(spec: &Spec) -> HashSet<(usize, usize)> {
    let mut adj = HashSet::new();
    for &(u, v) in &spec.edges {
        adj.insert((u, v));
        adj.insert((v, u));
    }
    adj
}

fn adjacent(adj: &HashSet<(usize, usize)>, u: usize, v: usize) -> bool {
    adj.contains(&(u, v))
}

#[test]
fn vertex_cover_covers_every_edge() {
    for (gi, spec) in graph_specs().iter().enumerate() {
        let (g, _ids) = build(spec);
        let cover: HashSet<usize> = min_weighted_vertex_cover(&g, None)
            .iter()
            .map(|nid| nid.index())
            .collect();
        for &(u, v) in &spec.edges {
            assert!(
                cover.contains(&u) || cover.contains(&v),
                "vertex cover (graph {gi}) misses edge ({u}, {v})"
            );
        }
    }
}

#[test]
fn independent_set_has_no_internal_edge() {
    for (gi, spec) in graph_specs().iter().enumerate() {
        let (g, _ids) = build(spec);
        let set: Vec<usize> = maximum_independent_set(&g)
            .iter()
            .map(|nid| nid.index())
            .collect();
        let adj = adjacency(spec);
        for i in 0..set.len() {
            for j in (i + 1)..set.len() {
                assert!(
                    !adjacent(&adj, set[i], set[j]),
                    "independent set (graph {gi}) contains adjacent pair ({}, {})",
                    set[i],
                    set[j]
                );
            }
        }
    }
}

#[test]
fn max_clique_is_fully_connected() {
    for (gi, spec) in graph_specs().iter().enumerate() {
        let (g, _ids) = build(spec);
        let clique: Vec<usize> = max_clique(&g).iter().map(|nid| nid.index()).collect();
        let adj = adjacency(spec);
        for i in 0..clique.len() {
            for j in (i + 1)..clique.len() {
                assert!(
                    adjacent(&adj, clique[i], clique[j]),
                    "max clique (graph {gi}) has non-adjacent pair ({}, {})",
                    clique[i],
                    clique[j]
                );
            }
        }
    }
}

#[test]
fn matching_is_vertex_disjoint_and_uses_real_edges() {
    for (gi, spec) in graph_specs().iter().enumerate() {
        let (g, _ids) = build(spec);
        let adj = adjacency(spec);
        let matching = min_maximal_matching(&g);
        let mut used: HashSet<usize> = HashSet::new();
        for (u, v) in &matching {
            let (a, b) = (u.index(), v.index());
            assert!(
                adjacent(&adj, a, b),
                "matching (graph {gi}) contains non-edge ({a}, {b})"
            );
            assert!(used.insert(a), "matching (graph {gi}) reuses node {a}");
            assert!(used.insert(b), "matching (graph {gi}) reuses node {b}");
        }
    }
}

#[test]
fn ramsey_returns_valid_clique_and_independent_set() {
    for (gi, spec) in graph_specs().iter().enumerate() {
        let (g, _ids) = build(spec);
        let adj = adjacency(spec);
        let (clique, independent) = ramsey_r2(&g);

        let clique: Vec<usize> = clique.iter().map(|nid| nid.index()).collect();
        for i in 0..clique.len() {
            for j in (i + 1)..clique.len() {
                assert!(
                    adjacent(&adj, clique[i], clique[j]),
                    "ramsey clique (graph {gi}) has non-adjacent pair"
                );
            }
        }

        let independent: Vec<usize> = independent.iter().map(|nid| nid.index()).collect();
        for i in 0..independent.len() {
            for j in (i + 1)..independent.len() {
                assert!(
                    !adjacent(&adj, independent[i], independent[j]),
                    "ramsey independent set (graph {gi}) has adjacent pair"
                );
            }
        }
    }
}

/// Brute-force unweighted diameter (max over all pairs of shortest hop count) on
/// a connected graph.
fn bfs_diameter(spec: &Spec) -> usize {
    let mut adj = vec![Vec::new(); spec.n];
    for &(u, v) in &spec.edges {
        adj[u].push(v);
        adj[v].push(u);
    }
    let mut diameter = 0;
    for src in 0..spec.n {
        let mut dist = vec![usize::MAX; spec.n];
        dist[src] = 0;
        let mut queue = VecDeque::from([src]);
        while let Some(node) = queue.pop_front() {
            for &next in &adj[node] {
                if dist[next] == usize::MAX {
                    dist[next] = dist[node] + 1;
                    diameter = diameter.max(dist[next]);
                    queue.push_back(next);
                }
            }
        }
    }
    diameter
}

#[test]
fn approximate_diameter_equals_true_diameter() {
    for (gi, spec) in connected_specs().iter().enumerate() {
        if spec.n < 2 {
            continue;
        }
        let mut g: Graph<i32, OrderedFloat<f64>> = Graph::new();
        let ids: Vec<NodeId> = (0..spec.n).map(|i| g.add_node(i as i32)).collect();
        for &(u, v) in &spec.edges {
            g.add_edge(ids[u], ids[v], OrderedFloat(1.0));
        }
        let got = approximate_diameter(&g)
            .unwrap_or_else(|e| panic!("approximate_diameter failed on graph {gi}: {e}"));
        let want = bfs_diameter(spec) as f64;
        assert!(
            (got - want).abs() < 1e-9,
            "approximate_diameter (graph {gi}): expected {want}, got {got}"
        );
    }
}
