//! NetworkX oracle replay tests for link-prediction scores.
//!
//! These tests replay a committed corpus of undirected graphs and reference
//! outputs generated by NetworkX (`scripts/gen_oracle_links_fixtures.py`,
//! regenerated with `make oracle-fixtures`). NetworkX is the oracle: a mismatch
//! here means the Graphina implementation disagrees with the reference on a
//! link-prediction score. The NetworkX dependency lives only in the generator,
//! so this test stays hermetic and needs no Python at build or run time.
//!
//! Scope: common neighbors, Jaccard coefficient, Adamic-Adar index,
//! preferential attachment, and resource allocation index, each scored over
//! every unordered node pair (both edges and non-edges) so the comparison
//! covers the full pair space. Each score matches the NetworkX definition for
//! the undirected, unweighted case; see the generator docstring for the
//! matching NetworkX call.

#![cfg(feature = "links")]

use graphina::core::types::{Graph, NodeId};
use graphina::links::allocation::resource_allocation_index;
use graphina::links::attachment::preferential_attachment;
use graphina::links::similarity::{adamic_adar_index, common_neighbors, jaccard_coefficient};
use serde::Deserialize;
use std::collections::HashMap;

#[derive(Deserialize)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    pairs: Vec<[usize; 2]>,
    common_neighbors: Vec<usize>,
    jaccard: Vec<f64>,
    adamic_adar: Vec<f64>,
    preferential_attachment: Vec<f64>,
    resource_allocation: Vec<f64>,
}

/// Slack tolerance: every score here is an exact rational under f64, so this
/// only absorbs the rounding of `ln` in Adamic-Adar.
const EPS: f64 = 1e-9;

fn load_corpus() -> Corpus {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/oracle/networkx_links_oracle.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read links oracle corpus at {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse links oracle: {e}"))
}

fn build_graph(case: &Case) -> (Graph<i32, f64>, Vec<NodeId>) {
    let mut g: Graph<i32, f64> = Graph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for e in &case.edges {
        g.add_edge(ids[e[0]], ids[e[1]], 1.0);
    }
    (g, ids)
}

/// The ebunch of node-pair handles to score, in corpus order.
fn ebunch(case: &Case, ids: &[NodeId]) -> Vec<(NodeId, NodeId)> {
    case.pairs.iter().map(|p| (ids[p[0]], ids[p[1]])).collect()
}

/// Reduce a NodeId-keyed predictor result to an index-keyed score map, with the
/// pair canonicalized as `(min, max)` so endpoint order cannot matter.
fn score_map(scored: Vec<((NodeId, NodeId), f64)>) -> HashMap<(usize, usize), f64> {
    scored
        .into_iter()
        .map(|((u, v), s)| {
            let (a, b) = (u.index(), v.index());
            ((a.min(b), a.max(b)), s)
        })
        .collect()
}

fn assert_f64(
    got_map: &HashMap<(usize, usize), f64>,
    case: &Case,
    expected: &[f64],
    measure: &str,
) {
    for (k, p) in case.pairs.iter().enumerate() {
        let key = (p[0].min(p[1]), p[0].max(p[1]));
        let got = *got_map
            .get(&key)
            .unwrap_or_else(|| panic!("{measure}: case {} missing pair {p:?}", case.id));
        let want = expected[k];
        assert!(
            (got - want).abs() < EPS,
            "{measure}: case {} pair {p:?}: expected {want}, got {got}",
            case.id
        );
    }
}

#[test]
fn oracle_common_neighbors() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        for (k, p) in case.pairs.iter().enumerate() {
            let got = common_neighbors(&g, ids[p[0]], ids[p[1]]);
            assert_eq!(
                got, case.common_neighbors[k],
                "common_neighbors: case {} pair {p:?}",
                case.id
            );
        }
    }
}

#[test]
fn oracle_jaccard_coefficient() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let eb = ebunch(&case, &ids);
        let map = score_map(jaccard_coefficient(&g, Some(&eb)));
        assert_f64(&map, &case, &case.jaccard, "jaccard");
    }
}

#[test]
fn oracle_adamic_adar_index() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let eb = ebunch(&case, &ids);
        let map = score_map(adamic_adar_index(&g, Some(&eb)));
        assert_f64(&map, &case, &case.adamic_adar, "adamic-adar");
    }
}

#[test]
fn oracle_preferential_attachment() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let eb = ebunch(&case, &ids);
        let map = score_map(preferential_attachment(&g, Some(&eb)));
        assert_f64(
            &map,
            &case,
            &case.preferential_attachment,
            "preferential-attachment",
        );
    }
}

#[test]
fn oracle_resource_allocation_index() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let eb = ebunch(&case, &ids);
        let map = score_map(resource_allocation_index(&g, Some(&eb)));
        assert_f64(
            &map,
            &case,
            &case.resource_allocation,
            "resource-allocation",
        );
    }
}
