//! NetworkX oracle replay tests.
//!
//! These tests replay a committed corpus of graphs and reference outputs
//! generated by NetworkX (`scripts/gen_oracle_fixtures.py`, regenerated with
//! `make oracle-fixtures`). NetworkX is the oracle: a mismatch here means the
//! Graphina implementation disagrees with the reference on a spec-unambiguous
//! algorithm. The NetworkX dependency lives only in the generator, so this test
//! stays hermetic and needs no Python at build or run time.
//!
//! Scope (first slice): connected components, degree, weighted shortest path
//! length (Dijkstra), and minimum spanning tree total weight and edge count.
//! The corpus graphs are simple, undirected, and integer-weighted, so the
//! comparisons are exact and free of convention differences. The MST is checked
//! by total weight and edge count, not edge set, because the tree is not unique
//! under weight ties.

use graphina::core::paths::dijkstra_path_f64;
use graphina::core::types::{Graph, NodeId};
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    weights: Vec<f64>,
    components: Vec<Vec<usize>>,
    degree: Vec<usize>,
    dijkstra: Vec<(usize, usize, f64)>,
    mst: Option<Mst>,
}

#[derive(Deserialize)]
struct Mst {
    weight: f64,
    edges: usize,
}

/// Tolerance for comparing sums of small integer weights stored as f64. The sums
/// are exact under f64, so this only guards against incidental representation
/// noise.
const EPS: f64 = 1e-9;

fn load_corpus() -> Corpus {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/oracle/networkx_oracle.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read oracle corpus at {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse oracle corpus: {e}"))
}

/// Build an `f64`-weighted undirected graph from a case, returning the node id
/// for each integer index 0..n.
fn build_graph(case: &Case) -> (Graph<i32, f64>, Vec<NodeId>) {
    let mut g: Graph<i32, f64> = Graph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for (e, &w) in case.edges.iter().zip(&case.weights) {
        g.add_edge(ids[e[0]], ids[e[1]], w);
    }
    (g, ids)
}

#[test]
fn oracle_degree() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        for (i, &expected) in case.degree.iter().enumerate() {
            assert_eq!(
                g.degree(ids[i]),
                Some(expected),
                "degree mismatch in case {} at node {i}",
                case.id
            );
        }
    }
}

#[test]
fn oracle_dijkstra() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        for s in 0..case.n {
            let (dist, _) = dijkstra_path_f64(&g, ids[s], None)
                .unwrap_or_else(|e| panic!("dijkstra failed in case {} from {s}: {e}", case.id));
            for &(_, t, expected) in case.dijkstra.iter().filter(|e| e.0 == s) {
                let got = dist[&ids[t]];
                if expected < 0.0 {
                    assert_eq!(
                        got, None,
                        "case {} expected {t} unreachable from {s}, got {got:?}",
                        case.id
                    );
                } else {
                    let got = got.unwrap_or_else(|| {
                        panic!("case {} expected {t} reachable from {s}, got None", case.id)
                    });
                    assert!(
                        (got - expected).abs() < EPS,
                        "case {} dijkstra {s}->{t}: expected {expected}, got {got}",
                        case.id
                    );
                }
            }
        }
    }
}

#[cfg(feature = "community")]
#[test]
fn oracle_components() {
    use graphina::community::connected_components::connected_components;

    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let _ = &ids;
        let mut got: Vec<Vec<usize>> = connected_components(&g)
            .into_iter()
            .map(|comp| {
                let mut v: Vec<usize> = comp.iter().map(|n| n.index()).collect();
                v.sort_unstable();
                v
            })
            .collect();
        got.sort();
        assert_eq!(
            got, case.components,
            "connected components mismatch in case {}",
            case.id
        );
    }
}

#[cfg(feature = "mst")]
#[test]
fn oracle_mst() {
    use graphina::mst::{boruvka_mst, kruskal_mst, prim_mst};
    use ordered_float::OrderedFloat;

    for case in load_corpus().cases {
        // The MST oracle is emitted only for connected graphs.
        let Some(expected) = case.mst else {
            continue;
        };

        let mut g: Graph<i32, OrderedFloat<f64>> = Graph::new();
        let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
        for (e, &w) in case.edges.iter().zip(&case.weights) {
            g.add_edge(ids[e[0]], ids[e[1]], OrderedFloat(w));
        }

        let results = [
            ("kruskal", kruskal_mst(&g)),
            ("prim", prim_mst(&g)),
            ("boruvka", boruvka_mst(&g)),
        ];
        for (name, result) in results {
            let (edges, total) =
                result.unwrap_or_else(|e| panic!("{name} MST failed in case {}: {e}", case.id));
            assert_eq!(
                edges.len(),
                expected.edges,
                "{name} MST edge count mismatch in case {}",
                case.id
            );
            assert!(
                (total.0 - expected.weight).abs() < EPS,
                "{name} MST weight mismatch in case {}: expected {}, got {}",
                case.id,
                expected.weight,
                total.0
            );
        }
    }
}
