//! NetworkX oracle replay tests for centrality measures.
//!
//! These tests replay a committed corpus of undirected graphs and reference
//! outputs generated by NetworkX (`scripts/gen_oracle_centrality_fixtures.py`,
//! regenerated with `make oracle-fixtures`). NetworkX is the oracle: a mismatch
//! here means the Graphina implementation disagrees with the reference on a
//! convention-pinned centrality measure. The NetworkX dependency lives only in
//! the generator, so this test stays hermetic and needs no Python at build or
//! run time.
//!
//! Scope: degree (raw counts), betweenness (unweighted, without endpoints, both
//! unnormalized and normalized), harmonic (weighted), and PageRank (weighted).
//! Each is pinned to the convention Graphina implements; see the generator
//! docstring for the matching NetworkX call. Comparisons use a slack tolerance
//! that absorbs floating-point and iteration differences.

#![cfg(feature = "centrality")]

use graphina::centrality::betweenness::betweenness_centrality;
use graphina::centrality::degree::degree_centrality;
use graphina::centrality::harmonic::harmonic_centrality;
use graphina::centrality::pagerank::pagerank;
use graphina::core::types::{Graph, NodeId};
use ordered_float::OrderedFloat;
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    weights: Vec<f64>,
    degree: Vec<f64>,
    betweenness_raw: Vec<f64>,
    betweenness_norm: Vec<f64>,
    closeness: Vec<f64>,
    harmonic: Vec<f64>,
    pagerank: Vec<f64>,
}

/// Slack tolerance: harmonic and betweenness are exact rationals under f64;
/// PageRank is iterative, so this absorbs convergence and rounding differences.
const EPS: f64 = 1e-6;

fn load_corpus() -> Corpus {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/oracle/networkx_centrality_oracle.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read centrality oracle corpus at {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse centrality oracle: {e}"))
}

/// Build an `OrderedFloat`-weighted undirected graph from a case (centrality
/// functions take `OrderedFloat<f64>` or a generic weight; `OrderedFloat` works
/// for all of them).
fn build_graph(case: &Case) -> (Graph<i32, OrderedFloat<f64>>, Vec<NodeId>) {
    let mut g: Graph<i32, OrderedFloat<f64>> = Graph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for (e, &w) in case.edges.iter().zip(&case.weights) {
        g.add_edge(ids[e[0]], ids[e[1]], OrderedFloat(w));
    }
    (g, ids)
}

/// Assert that an actual centrality map matches the oracle vector, indexed by
/// node 0..n, within `EPS`.
fn assert_close(
    actual: &graphina::core::types::NodeMap<f64>,
    expected: &[f64],
    ids: &[NodeId],
    measure: &str,
    id: &str,
) {
    for (i, &want) in expected.iter().enumerate() {
        let got = *actual
            .get(&ids[i])
            .unwrap_or_else(|| panic!("{measure}: case {id} missing node {i}"));
        assert!(
            (got - want).abs() < EPS,
            "{measure}: case {id} node {i}: expected {want}, got {got}"
        );
    }
}

#[test]
fn oracle_degree_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let dc = degree_centrality(&g)
            .unwrap_or_else(|e| panic!("degree_centrality failed in case {}: {e}", case.id));
        assert_close(&dc, &case.degree, &ids, "degree", &case.id);
    }
}

#[test]
fn oracle_betweenness_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let raw = betweenness_centrality(&g, false)
            .unwrap_or_else(|e| panic!("betweenness (raw) failed in case {}: {e}", case.id));
        assert_close(
            &raw,
            &case.betweenness_raw,
            &ids,
            "betweenness-raw",
            &case.id,
        );

        let norm = betweenness_centrality(&g, true)
            .unwrap_or_else(|e| panic!("betweenness (norm) failed in case {}: {e}", case.id));
        assert_close(
            &norm,
            &case.betweenness_norm,
            &ids,
            "betweenness-norm",
            &case.id,
        );
    }
}

#[test]
fn oracle_closeness_centrality() {
    use graphina::centrality::closeness::closeness_centrality;

    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let cc = closeness_centrality(&g)
            .unwrap_or_else(|e| panic!("closeness_centrality failed in case {}: {e}", case.id));
        assert_close(&cc, &case.closeness, &ids, "closeness", &case.id);
    }
}

#[test]
fn oracle_harmonic_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let hc = harmonic_centrality(&g)
            .unwrap_or_else(|e| panic!("harmonic_centrality failed in case {}: {e}", case.id));
        assert_close(&hc, &case.harmonic, &ids, "harmonic", &case.id);
    }
}

#[test]
fn oracle_pagerank() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let pr = pagerank(&g, 0.85, 2000, 1e-12, None)
            .unwrap_or_else(|e| panic!("pagerank failed in case {}: {e}", case.id));
        assert_close(&pr, &case.pagerank, &ids, "pagerank", &case.id);
    }
}
