//! NetworkX oracle replay tests for spectral centralities.
//!
//! These tests replay a committed corpus of connected, undirected graphs and
//! reference outputs generated by NetworkX
//! (`scripts/gen_oracle_spectral_fixtures.py`, regenerated with
//! `make oracle-fixtures`). NetworkX is the oracle: a mismatch here means the
//! Graphina implementation disagrees with the reference on the structure of the
//! eigenvector or Katz centrality vector. The NetworkX dependency lives only in
//! the generator, so this test stays hermetic and needs no Python at build or
//! run time.
//!
//! Eigenvector and Katz centrality are defined only up to a positive scale
//! factor, and Graphina and NetworkX normalize differently (Graphina scales the
//! eigenvector to sum to n and returns Katz unnormalized; NetworkX uses unit L2
//! norm). The corpus stores the L2-normalized reference, and these tests
//! L2-normalize Graphina's output before comparing, so the comparison checks the
//! centrality structure rather than the normalization convention.

#![cfg(feature = "centrality")]

use graphina::centrality::eigenvector::eigenvector_centrality;
use graphina::centrality::katz::katz_centrality;
use graphina::core::types::{Graph, NodeId};
use ordered_float::OrderedFloat;
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    eigenvector: Vec<f64>,
    katz: Vec<f64>,
    laplacian: Vec<f64>,
}

/// The Katz attenuation factor must match the generator (`ALPHA`).
const ALPHA: f64 = 0.05;
const EPS: f64 = 1e-6;

fn load_corpus() -> Corpus {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/oracle/networkx_spectral_oracle.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read spectral oracle corpus at {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse spectral oracle: {e}"))
}

fn build_graph(case: &Case) -> (Graph<i32, OrderedFloat<f64>>, Vec<NodeId>) {
    let mut g: Graph<i32, OrderedFloat<f64>> = Graph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for e in &case.edges {
        g.add_edge(ids[e[0]], ids[e[1]], OrderedFloat(1.0));
    }
    (g, ids)
}

/// Extract the centrality vector in node-index order and scale it to unit L2
/// norm, matching the normalization the oracle stores.
fn l2_normalized(
    map: &graphina::core::types::NodeMap<f64>,
    ids: &[NodeId],
    measure: &str,
    id: &str,
) -> Vec<f64> {
    let vals: Vec<f64> = ids
        .iter()
        .map(|n| {
            *map.get(n)
                .unwrap_or_else(|| panic!("{measure}: case {id} missing a node"))
        })
        .collect();
    let norm = vals.iter().map(|v| v * v).sum::<f64>().sqrt();
    if norm == 0.0 {
        vals
    } else {
        vals.into_iter().map(|v| v / norm).collect()
    }
}

#[test]
fn oracle_eigenvector_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let ec = eigenvector_centrality(&g, 10_000, 1e-10)
            .unwrap_or_else(|e| panic!("eigenvector_centrality failed in case {}: {e}", case.id));
        let got = l2_normalized(&ec, &ids, "eigenvector", &case.id);
        for (i, &want) in case.eigenvector.iter().enumerate() {
            assert!(
                (got[i] - want).abs() < EPS,
                "eigenvector: case {} node {i}: expected {want}, got {}",
                case.id,
                got[i]
            );
        }
    }
}

#[test]
fn oracle_laplacian_centrality() {
    use graphina::centrality::other::laplacian_centrality;

    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let lc = laplacian_centrality(&g)
            .unwrap_or_else(|e| panic!("laplacian_centrality failed in case {}: {e}", case.id));
        for (i, &want) in case.laplacian.iter().enumerate() {
            let got = *lc
                .get(&ids[i])
                .unwrap_or_else(|| panic!("laplacian: case {} missing node {i}", case.id));
            assert!(
                (got - want).abs() < EPS,
                "laplacian: case {} node {i}: expected {want}, got {got}",
                case.id
            );
        }
    }
}

#[test]
fn oracle_katz_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let kc = katz_centrality(&g, ALPHA, None, 10_000, 1e-10)
            .unwrap_or_else(|e| panic!("katz_centrality failed in case {}: {e}", case.id));
        let got = l2_normalized(&kc, &ids, "katz", &case.id);
        for (i, &want) in case.katz.iter().enumerate() {
            assert!(
                (got[i] - want).abs() < EPS,
                "katz: case {} node {i}: expected {want}, got {}",
                case.id,
                got[i]
            );
        }
    }
}
