//! NetworkX oracle replay tests for directed graphs.
//!
//! These tests replay a committed corpus of directed graphs and reference
//! outputs generated by NetworkX (`scripts/gen_oracle_directed_fixtures.py`,
//! regenerated with `make oracle-fixtures`). NetworkX is the oracle: a mismatch
//! here means the Graphina implementation disagrees with the reference on a
//! spec-unambiguous algorithm. The NetworkX dependency lives only in the
//! generator, so this test stays hermetic and needs no Python at build or run time.
//!
//! Scope: in, out, and total degree, and directed shortest path lengths. The
//! corpus uses positive integer weights, so there are no negative cycles and the
//! single distance oracle (`sp_len`) is the correct reference for every shortest
//! path algorithm Graphina exposes on directed graphs: per-source Dijkstra and
//! Bellman-Ford, and all-pairs Floyd-Warshall and Johnson. Integer weight sums
//! are exact under f64, so the comparisons need no tolerance beyond guarding
//! against incidental representation noise.

use graphina::core::paths::{bellman_ford, dijkstra_path_f64, floyd_warshall, johnson};
use graphina::core::types::{Digraph, NodeId};
use ordered_float::OrderedFloat;
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    weights: Vec<f64>,
    degree: Degree,
    sp_len: Vec<(usize, usize, f64)>,
    wcc: Vec<Vec<usize>>,
    scc: Vec<Vec<usize>>,
}

#[derive(Deserialize)]
struct Degree {
    #[serde(rename = "in")]
    in_: Vec<usize>,
    out: Vec<usize>,
    total: Vec<usize>,
}

/// Tolerance for comparing sums of small integer weights stored as f64. The sums
/// are exact under f64, so this only guards against incidental representation
/// noise.
const EPS: f64 = 1e-9;

fn load_corpus() -> Corpus {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/oracle/networkx_directed_oracle.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read directed oracle corpus at {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse directed oracle: {e}"))
}

/// Build an `f64`-weighted directed graph from a case, returning the node id for
/// each integer index 0..n.
fn build_graph(case: &Case) -> (Digraph<i32, f64>, Vec<NodeId>) {
    let mut g: Digraph<i32, f64> = Digraph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for (e, &w) in case.edges.iter().zip(&case.weights) {
        g.add_edge(ids[e[0]], ids[e[1]], w);
    }
    (g, ids)
}

/// Build the `OrderedFloat`-weighted directed graph Johnson requires (its weight
/// bound needs a total order).
fn build_ordered_graph(case: &Case) -> (Digraph<i32, OrderedFloat<f64>>, Vec<NodeId>) {
    let mut g: Digraph<i32, OrderedFloat<f64>> = Digraph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for (e, &w) in case.edges.iter().zip(&case.weights) {
        g.add_edge(ids[e[0]], ids[e[1]], OrderedFloat(w));
    }
    (g, ids)
}

/// Compare an actual distance (`None` for unreachable) against the oracle entry,
/// where a negative oracle weight marks an unreachable pair.
fn check(actual: Option<f64>, expected: f64, algo: &str, id: &str, s: usize, t: usize) {
    if expected < 0.0 {
        assert_eq!(
            actual, None,
            "{algo}: case {id} expected {t} unreachable from {s}, got {actual:?}"
        );
    } else {
        let got =
            actual.unwrap_or_else(|| panic!("{algo}: case {id} expected {t} reachable from {s}"));
        assert!(
            (got - expected).abs() < EPS,
            "{algo}: case {id} {s}->{t}: expected {expected}, got {got}"
        );
    }
}

#[test]
fn oracle_directed_degree() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        for (i, &id) in ids.iter().enumerate() {
            assert_eq!(
                g.in_degree(id),
                Some(case.degree.in_[i]),
                "in-degree mismatch in case {} at node {i}",
                case.id
            );
            assert_eq!(
                g.out_degree(id),
                Some(case.degree.out[i]),
                "out-degree mismatch in case {} at node {i}",
                case.id
            );
            assert_eq!(
                g.degree(id),
                Some(case.degree.total[i]),
                "total degree mismatch in case {} at node {i}",
                case.id
            );
        }
    }
}

#[test]
fn oracle_directed_dijkstra() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        for s in 0..case.n {
            let (dist, _) = dijkstra_path_f64(&g, ids[s], None)
                .unwrap_or_else(|e| panic!("dijkstra failed in case {} from {s}: {e}", case.id));
            for &(_, t, expected) in case.sp_len.iter().filter(|e| e.0 == s) {
                check(dist[&ids[t]], expected, "dijkstra", &case.id, s, t);
            }
        }
    }
}

#[test]
fn oracle_directed_bellman_ford() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        for s in 0..case.n {
            let dist = bellman_ford(&g, ids[s]).unwrap_or_else(|| {
                panic!("bellman-ford reported a negative cycle in case {}", case.id)
            });
            for &(_, t, expected) in case.sp_len.iter().filter(|e| e.0 == s) {
                check(dist[&ids[t]], expected, "bellman-ford", &case.id, s, t);
            }
        }
    }
}

#[test]
fn oracle_directed_floyd_warshall() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let dist = floyd_warshall(&g)
            .unwrap_or_else(|| panic!("floyd-warshall reported a negative cycle in {}", case.id));
        for &(s, t, expected) in &case.sp_len {
            let got = dist
                .get(&ids[s])
                .and_then(|row| row.get(&ids[t]))
                .copied()
                .flatten();
            check(got, expected, "floyd-warshall", &case.id, s, t);
        }
    }
}

/// Canonicalize a partition (`Vec<Vec<NodeId>>`) into sorted integer-index lists
/// for comparison against the oracle.
#[cfg(feature = "community")]
fn sorted_partition(components: Vec<Vec<NodeId>>) -> Vec<Vec<usize>> {
    let mut parts: Vec<Vec<usize>> = components
        .into_iter()
        .map(|c| {
            let mut v: Vec<usize> = c.iter().map(|n| n.index()).collect();
            v.sort_unstable();
            v
        })
        .collect();
    parts.sort();
    parts
}

#[cfg(feature = "community")]
#[test]
fn oracle_directed_wcc() {
    use graphina::community::connected_components::weakly_connected_components;

    for case in load_corpus().cases {
        let (g, _ids) = build_graph(&case);
        assert_eq!(
            sorted_partition(weakly_connected_components(&g)),
            case.wcc,
            "weakly connected components mismatch in case {}",
            case.id
        );
    }
}

#[cfg(feature = "community")]
#[test]
fn oracle_directed_scc() {
    use graphina::community::connected_components::strongly_connected_components;

    for case in load_corpus().cases {
        let (g, _ids) = build_graph(&case);
        assert_eq!(
            sorted_partition(strongly_connected_components(&g)),
            case.scc,
            "strongly connected components mismatch in case {}",
            case.id
        );
    }
}

#[test]
fn oracle_directed_johnson() {
    for case in load_corpus().cases {
        let (g, ids) = build_ordered_graph(&case);
        let dist = johnson(&g)
            .unwrap_or_else(|| panic!("johnson reported a negative cycle in {}", case.id));
        for &(s, t, expected) in &case.sp_len {
            let got = dist
                .get(&ids[s])
                .and_then(|row| row.get(&ids[t]))
                .copied()
                .flatten()
                .map(|w| w.0);
            check(got, expected, "johnson", &case.id, s, t);
        }
    }
}
