//! NetworkX oracle replay tests for graphs with self-loops.
//!
//! These tests replay a committed corpus of graphs in which several nodes carry
//! a self-loop, with reference outputs generated by NetworkX
//! (`scripts/gen_oracle_self_loop_fixtures.py`, regenerated with
//! `make oracle-fixtures`). The other oracle corpora use simple graphs, so this
//! is the only place the self-loop convention is checked against the reference.
//! The NetworkX dependency lives only in the generator, so this test stays
//! hermetic and needs no Python at build or run time.
//!
//! Conventions pinned: a self-loop is a single edge (one diagonal entry, added
//! once to a node's strength in PageRank, personalized PageRank, and
//! eigenvector centrality), and a self-loop does not make a node its own
//! neighbor for clustering, triangle counts, or transitivity. The parallel
//! twins and the approximation module's average clustering are checked on the
//! same corpus.

#![cfg(all(feature = "centrality", feature = "metrics"))]

use graphina::centrality::eigenvector::eigenvector_centrality;
use graphina::centrality::pagerank::pagerank;
use graphina::centrality::personalized_pagerank::personalized_page_rank;
use graphina::core::types::{Digraph, Graph, NodeId, NodeMap};
use graphina::metrics::{
    average_clustering_coefficient, clustering_coefficient, transitivity, triangles,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    undirected: Vec<UndirectedCase>,
    directed: Vec<DirectedCase>,
}

#[derive(Deserialize)]
struct UndirectedCase {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    weights: Vec<f64>,
    pagerank: Vec<f64>,
    personalization: Vec<f64>,
    personalized_pagerank: Vec<f64>,
    eigenvector: Vec<f64>,
    transitivity: f64,
    average_clustering: f64,
    clustering: Vec<f64>,
    triangles: Vec<usize>,
}

#[derive(Deserialize)]
struct DirectedCase {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    weights: Vec<f64>,
    pagerank: Vec<f64>,
}

/// Slack tolerance: clustering values are exact rationals under f64; the
/// iterative measures need room for convergence and rounding differences.
const EPS: f64 = 1e-6;

fn load_corpus() -> Corpus {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/oracle/networkx_self_loop_oracle.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read self-loop oracle corpus at {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse self-loop oracle: {e}"))
}

fn build_undirected(case: &UndirectedCase) -> (Graph<i32, f64>, Vec<NodeId>) {
    let mut g: Graph<i32, f64> = Graph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for (e, &w) in case.edges.iter().zip(&case.weights) {
        g.add_edge(ids[e[0]], ids[e[1]], w);
    }
    assert!(
        case.edges.iter().any(|e| e[0] == e[1]),
        "case {} has no self-loop; the corpus is not exercising the convention",
        case.id
    );
    (g, ids)
}

fn build_directed(case: &DirectedCase) -> (Digraph<i32, f64>, Vec<NodeId>) {
    let mut g: Digraph<i32, f64> = Digraph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for (e, &w) in case.edges.iter().zip(&case.weights) {
        g.add_edge(ids[e[0]], ids[e[1]], w);
    }
    (g, ids)
}

fn assert_close<S: std::hash::BuildHasher>(
    actual: &std::collections::HashMap<NodeId, f64, S>,
    expected: &[f64],
    ids: &[NodeId],
    measure: &str,
    id: &str,
) {
    for (i, &want) in expected.iter().enumerate() {
        let got = *actual
            .get(&ids[i])
            .unwrap_or_else(|| panic!("{measure}: case {id} missing node {i}"));
        assert!(
            (got - want).abs() < EPS,
            "{measure}: case {id} node {i}: expected {want}, got {got}"
        );
    }
}

fn l2_normalized(map: &NodeMap<f64>) -> NodeMap<f64> {
    let norm = map.values().map(|v| v * v).sum::<f64>().sqrt();
    map.iter().map(|(&k, &v)| (k, v / norm)).collect()
}

#[test]
fn oracle_self_loop_pagerank() {
    let corpus = load_corpus();
    for case in &corpus.undirected {
        let (g, ids) = build_undirected(case);
        let pr = pagerank(&g, 0.85, 5000, 1e-12, None)
            .unwrap_or_else(|e| panic!("pagerank failed in case {}: {e}", case.id));
        assert_close(&pr, &case.pagerank, &ids, "pagerank", &case.id);
    }
    for case in &corpus.directed {
        let (g, ids) = build_directed(case);
        let pr = pagerank(&g, 0.85, 5000, 1e-12, None)
            .unwrap_or_else(|e| panic!("pagerank failed in case {}: {e}", case.id));
        assert_close(&pr, &case.pagerank, &ids, "pagerank", &case.id);
    }
}

#[test]
fn oracle_self_loop_personalized_pagerank() {
    for case in load_corpus().undirected {
        let (g, ids) = build_undirected(&case);
        let ranks =
            personalized_page_rank(&g, Some(case.personalization.clone()), 0.85, 1e-12, 5000)
                .unwrap_or_else(|e| {
                    panic!("personalized pagerank failed in case {}: {e}", case.id)
                });
        let map: NodeMap<f64> = ids.iter().copied().zip(ranks).collect();
        assert_close(
            &map,
            &case.personalized_pagerank,
            &ids,
            "personalized_pagerank",
            &case.id,
        );
    }
}

#[test]
fn oracle_self_loop_eigenvector() {
    for case in load_corpus().undirected {
        let (g, ids) = build_undirected(&case);
        let ev = eigenvector_centrality(&g, 20_000, 1e-10)
            .unwrap_or_else(|e| panic!("eigenvector failed in case {}: {e}", case.id));
        assert_close(
            &l2_normalized(&ev),
            &case.eigenvector,
            &ids,
            "eigenvector",
            &case.id,
        );
    }
}

#[test]
fn oracle_self_loop_clustering_and_triangles() {
    for case in load_corpus().undirected {
        let (g, ids) = build_undirected(&case);

        let t = transitivity(&g);
        assert!(
            (t - case.transitivity).abs() < EPS,
            "transitivity: case {}: expected {}, got {t}",
            case.id,
            case.transitivity
        );
        let ac = average_clustering_coefficient(&g);
        assert!(
            (ac - case.average_clustering).abs() < EPS,
            "average_clustering: case {}: expected {}, got {ac}",
            case.id,
            case.average_clustering
        );
        for (i, &want) in case.clustering.iter().enumerate() {
            let got = clustering_coefficient(&g, ids[i]);
            assert!(
                (got - want).abs() < EPS,
                "clustering: case {} node {i}: expected {want}, got {got}",
                case.id
            );
        }
        for (i, &want) in case.triangles.iter().enumerate() {
            let got = triangles(&g, ids[i]);
            assert_eq!(got, want, "triangles: case {} node {i}", case.id);
        }
    }
}

#[cfg(feature = "parallel")]
#[test]
fn oracle_self_loop_parallel_twins() {
    use graphina::parallel::{
        clustering_coefficients_parallel, pagerank_parallel, triangles_parallel,
    };

    let corpus = load_corpus();
    for case in &corpus.undirected {
        let (g, ids) = build_undirected(case);
        let pr = pagerank_parallel(&g, 0.85, 5000, 1e-12, None);
        assert_close(&pr, &case.pagerank, &ids, "pagerank_parallel", &case.id);
        let cc = clustering_coefficients_parallel(&g);
        assert_close(&cc, &case.clustering, &ids, "clustering_parallel", &case.id);
        let tri = triangles_parallel(&g);
        for (i, &want) in case.triangles.iter().enumerate() {
            assert_eq!(
                tri[&ids[i]], want,
                "triangles_parallel: case {} node {i}",
                case.id
            );
        }
    }
    for case in &corpus.directed {
        let (g, ids) = build_directed(case);
        let pr = pagerank_parallel(&g, 0.85, 5000, 1e-12, None);
        assert_close(&pr, &case.pagerank, &ids, "pagerank_parallel", &case.id);
    }
}

#[cfg(feature = "approximation")]
#[test]
fn oracle_self_loop_approximation_average_clustering() {
    use graphina::approximation::clustering::average_clustering;

    for case in load_corpus().undirected {
        let (g, _ids) = build_undirected(&case);
        let ac = average_clustering(&g);
        assert!(
            (ac - case.average_clustering).abs() < EPS,
            "approximation average_clustering: case {}: expected {}, got {ac}",
            case.id,
            case.average_clustering
        );
    }
}
