//! NetworkX oracle replay tests for graph metrics.
//!
//! These tests replay a committed corpus of simple, connected, undirected,
//! unweighted graphs and reference outputs generated by NetworkX
//! (`scripts/gen_oracle_metrics_fixtures.py`, regenerated with
//! `make oracle-fixtures`). NetworkX is the oracle: a mismatch here means the
//! Graphina implementation disagrees with the reference on a structural metric.
//! The NetworkX dependency lives only in the generator, so this test stays
//! hermetic and needs no Python at build or run time.
//!
//! Scope: diameter, radius, average shortest path length (all unweighted),
//! transitivity, average clustering, per-node clustering, per-node triangle
//! counts, and degree assortativity. The graphs are connected so the
//! distance-based metrics are defined; see the generator docstring for the
//! matching NetworkX call for each metric.

#![cfg(feature = "metrics")]

use graphina::core::types::{Graph, NodeId};
use graphina::metrics::{
    assortativity, average_clustering_coefficient, average_path_length, clustering_coefficient,
    diameter, radius, transitivity, triangles,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    diameter: usize,
    radius: usize,
    average_path_length: f64,
    transitivity: f64,
    average_clustering: f64,
    clustering: Vec<f64>,
    triangles: Vec<usize>,
    assortativity: Option<f64>,
}

/// Slack tolerance: clustering and transitivity are rationals under f64, and the
/// path-length average is an exact rational of small integers, so this only
/// absorbs floating-point rounding.
const EPS: f64 = 1e-9;

fn load_corpus() -> Corpus {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/oracle/networkx_metrics_oracle.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read metrics oracle corpus at {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse metrics oracle: {e}"))
}

fn build_graph(case: &Case) -> (Graph<i32, f64>, Vec<NodeId>) {
    let mut g: Graph<i32, f64> = Graph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for e in &case.edges {
        g.add_edge(ids[e[0]], ids[e[1]], 1.0);
    }
    (g, ids)
}

#[test]
fn oracle_diameter_radius() {
    for case in load_corpus().cases {
        let (g, _ids) = build_graph(&case);
        let d = diameter(&g)
            .unwrap_or_else(|| panic!("diameter returned None on connected case {}", case.id));
        assert_eq!(d, case.diameter, "diameter: case {}", case.id);
        let r = radius(&g)
            .unwrap_or_else(|| panic!("radius returned None on connected case {}", case.id));
        assert_eq!(r, case.radius, "radius: case {}", case.id);
    }
}

#[test]
fn oracle_average_path_length() {
    for case in load_corpus().cases {
        let (g, _ids) = build_graph(&case);
        let apl = average_path_length(&g).unwrap_or_else(|| {
            panic!(
                "average_path_length returned None on connected case {}",
                case.id
            )
        });
        assert!(
            (apl - case.average_path_length).abs() < EPS,
            "average_path_length: case {}: expected {}, got {apl}",
            case.id,
            case.average_path_length
        );
    }
}

#[test]
fn oracle_transitivity_and_clustering() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);

        let t = transitivity(&g);
        assert!(
            (t - case.transitivity).abs() < EPS,
            "transitivity: case {}: expected {}, got {t}",
            case.id,
            case.transitivity
        );

        let ac = average_clustering_coefficient(&g);
        assert!(
            (ac - case.average_clustering).abs() < EPS,
            "average_clustering: case {}: expected {}, got {ac}",
            case.id,
            case.average_clustering
        );

        for (i, &want) in case.clustering.iter().enumerate() {
            let got = clustering_coefficient(&g, ids[i]);
            assert!(
                (got - want).abs() < EPS,
                "clustering: case {} node {i}: expected {want}, got {got}",
                case.id
            );
        }
    }
}

#[test]
fn oracle_triangles() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        for (i, &want) in case.triangles.iter().enumerate() {
            let got = triangles(&g, ids[i]);
            assert_eq!(got, want, "triangles: case {} node {i}", case.id);
        }
    }
}

#[test]
fn oracle_assortativity() {
    for case in load_corpus().cases {
        let Some(want) = case.assortativity else {
            // NetworkX reports NaN (undefined) when degree variance is zero;
            // Graphina returns 0.0 by convention, so there is nothing to pin.
            continue;
        };
        let (g, _ids) = build_graph(&case);
        let got = assortativity(&g);
        assert!(
            (got - want).abs() < EPS,
            "assortativity: case {}: expected {want}, got {got}",
            case.id
        );
    }
}
