//! NetworkX oracle replay tests for centrality measures on directed graphs.
//!
//! These tests replay a committed corpus of directed graphs and reference
//! outputs generated by NetworkX
//! (`scripts/gen_oracle_directed_centrality_fixtures.py`, regenerated with
//! `make oracle-fixtures`). NetworkX is the oracle: a mismatch here means the
//! Graphina implementation disagrees with the reference on a convention-pinned
//! centrality measure. The NetworkX dependency lives only in the generator, so
//! this test stays hermetic and needs no Python at build or run time.
//!
//! Scope: in/out/total degree, betweenness (unweighted, without endpoints, both
//! normalizations), closeness and harmonic (weighted, out-distance), and
//! PageRank (weighted). Closeness and harmonic use distances out of each node,
//! so the generator computes their reference on the reversed graph.

#![cfg(feature = "centrality")]

use graphina::centrality::betweenness::betweenness_centrality;
use graphina::centrality::closeness::closeness_centrality;
use graphina::centrality::degree::{
    degree_centrality, in_degree_centrality, out_degree_centrality,
};
use graphina::centrality::harmonic::harmonic_centrality;
use graphina::centrality::pagerank::pagerank;
use graphina::core::types::{Digraph, NodeId};
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    n: usize,
    edges: Vec<[usize; 2]>,
    weights: Vec<f64>,
    degree: Degree,
    betweenness_raw: Vec<f64>,
    betweenness_norm: Vec<f64>,
    closeness: Vec<f64>,
    harmonic: Vec<f64>,
    pagerank: Vec<f64>,
}

#[derive(Deserialize)]
struct Degree {
    #[serde(rename = "in")]
    in_: Vec<f64>,
    out: Vec<f64>,
    total: Vec<f64>,
}

const EPS: f64 = 1e-6;

fn load_corpus() -> Corpus {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/oracle/networkx_directed_centrality_oracle.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read directed centrality oracle at {path}: {e}"));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("failed to parse directed centrality: {e}"))
}

fn build_graph(case: &Case) -> (Digraph<i32, f64>, Vec<NodeId>) {
    let mut g: Digraph<i32, f64> = Digraph::new();
    let ids: Vec<NodeId> = (0..case.n).map(|i| g.add_node(i as i32)).collect();
    for (e, &w) in case.edges.iter().zip(&case.weights) {
        g.add_edge(ids[e[0]], ids[e[1]], w);
    }
    (g, ids)
}

fn assert_close(
    actual: &graphina::core::types::NodeMap<f64>,
    expected: &[f64],
    ids: &[NodeId],
    measure: &str,
    id: &str,
) {
    for (i, &want) in expected.iter().enumerate() {
        let got = *actual
            .get(&ids[i])
            .unwrap_or_else(|| panic!("{measure}: case {id} missing node {i}"));
        assert!(
            (got - want).abs() < EPS,
            "{measure}: case {id} node {i}: expected {want}, got {got}"
        );
    }
}

#[test]
fn oracle_directed_degree_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let total = degree_centrality(&g)
            .unwrap_or_else(|e| panic!("degree_centrality failed in case {}: {e}", case.id));
        let ind = in_degree_centrality(&g)
            .unwrap_or_else(|e| panic!("in_degree_centrality failed in case {}: {e}", case.id));
        let outd = out_degree_centrality(&g)
            .unwrap_or_else(|e| panic!("out_degree_centrality failed in case {}: {e}", case.id));
        assert_close(&ind, &case.degree.in_, &ids, "in-degree", &case.id);
        assert_close(&outd, &case.degree.out, &ids, "out-degree", &case.id);
        assert_close(&total, &case.degree.total, &ids, "total-degree", &case.id);
    }
}

#[test]
fn oracle_directed_betweenness_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let raw = betweenness_centrality(&g, false)
            .unwrap_or_else(|e| panic!("betweenness (raw) failed in case {}: {e}", case.id));
        assert_close(
            &raw,
            &case.betweenness_raw,
            &ids,
            "betweenness-raw",
            &case.id,
        );
        let norm = betweenness_centrality(&g, true)
            .unwrap_or_else(|e| panic!("betweenness (norm) failed in case {}: {e}", case.id));
        assert_close(
            &norm,
            &case.betweenness_norm,
            &ids,
            "betweenness-norm",
            &case.id,
        );
    }
}

#[test]
fn oracle_directed_closeness_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let cc = closeness_centrality(&g)
            .unwrap_or_else(|e| panic!("closeness_centrality failed in case {}: {e}", case.id));
        assert_close(&cc, &case.closeness, &ids, "closeness", &case.id);
    }
}

#[test]
fn oracle_directed_harmonic_centrality() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let hc = harmonic_centrality(&g)
            .unwrap_or_else(|e| panic!("harmonic_centrality failed in case {}: {e}", case.id));
        assert_close(&hc, &case.harmonic, &ids, "harmonic", &case.id);
    }
}

#[test]
fn oracle_directed_pagerank() {
    for case in load_corpus().cases {
        let (g, ids) = build_graph(&case);
        let pr = pagerank(&g, 0.85, 2000, 1e-12, None)
            .unwrap_or_else(|e| panic!("pagerank failed in case {}: {e}", case.id));
        assert_close(&pr, &case.pagerank, &ids, "pagerank", &case.id);
    }
}
