#[cfg(feature = "approximation-clique")]
pub mod clique;
#[cfg(feature = "approximation-clustering")]
pub mod clustering;
#[cfg(feature = "approximation-connectivity")]
pub mod connectivity;
#[cfg(feature = "approximation-diameter")]
pub mod diameter;
#[cfg(feature = "approximation-independent-set")]
pub mod independent_set;
#[cfg(feature = "approximation-matching")]
pub mod matching;
#[cfg(feature = "approximation-ramsey")]
pub mod ramsey;
#[cfg(feature = "approximation-subgraph")]
pub mod subgraph;
#[cfg(feature = "approximation-treewidth")]
pub mod treewidth;
#[cfg(feature = "approximation-tsp")]
pub mod tsp;
#[cfg(feature = "approximation-vertex-cover")]
pub mod vertex_cover;
